site_name: BDRC developer portal
repo_name: evanyerburgh/docs
repo_url: https://github.com/evanyerburgh/docs
edit_uri: "blob/master/docs/docs"

site_author: Evan Yerburgh and Elie Roux
site_description: >-
  Documentation for BDRC's free open source software tools.
copyright: Copyright &copy; 2023 BDRC

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: logo.png
  features:
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - navigation.expand

nav:
  - Home: index.md
  - Pecha Data:
    - Test: ` `test.md
    
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - mkdocstrings
  - blog
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/buda-base